name: Update YouTube Videos

on:
  schedule:
    - cron: "0 * * * *" # runs every hour
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Update README with latest YouTube videos
        uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCipSxT7a3rn81vGLw9lqRkg # replace this with your real channel ID
          youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
          comment_tag_name: YOUTUBE-CARDS
          max_videos: 3
          show_duration: true
